version: '2.1'

services:
  sut:
    image: balena/jellyfish-sut:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - LOGLEVEL=error
    secrets:
      - integration_balena_api_private_key
      - integration_balena_api_public_key_production
    networks:
      - internal

secrets:
  integration_balena_api_private_key:
    file: ./.balena/secrets/integration_balena_api_private_key
  integration_balena_api_public_key_production:
    file: ./.balena/secrets/integration_balena_api_public_key_production
