version: '3'

env:
  INTEGRATION_BALENA_API_PRIVATE_KEY:
    sh: cat /run/secrets/integration_balena_api_private_key
  INTEGRATION_BALENA_API_PUBLIC_KEY_PRODUCTION:
    sh: cat /run/secrets/integration_balena_api_public_key_production

tasks:
  test:
    cmds:
      - npm run test:integration
